[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--version"

[[plugins]]
  package = "@netlify/plugin-pnpm"

[dev]
  command = "pnpm run dev"
  port = 8888
  targetPort = 9000
  framework = "#custom"
  autoLaunch = true
  npmClient = "pnpm"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
